name: 'Build'
description: 'Build using blacksmith runners and cache'
inputs:
  node-version:
    description: 'Node Version'
    required: false
    default: '20'
  packages:
    description: 'Package glob to build. Example: "@scalar/api-reference" or "packages/*"'
    required: true
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Check turbo cache dir
      shell: bash
      run: echo $TURBO_CACHE_DIR
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
    - name: Use Blacksmith Node.js ${{ inputs.node-version }}
      uses: useblacksmith/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Persist turbo cache
      uses: useblacksmith/stickydisk@v1
      with:
        key: ${{ github.repository }}-${{ inputs.node-version }}-turbo-cache
        path: ${{ env.TURBO_CACHE_DIR }}
    - name: Check turbo cache dir
      shell: bash
      run: echo Connecting $TURBO_CACHE_DIR on ${{ github.repository }}-${{ inputs.node-version }}-turbo-cache
    - name: Install dependencies
      shell: bash
      run: pnpm install
    - name: Build specified packages
      shell: bash
      run: pnpm turbo --concurrency=100% --filter '${{inputs.packages}}' build
      env:
        NODE_OPTIONS: '--max_old_space_size=8192'
