name: CI

# This workflow runs on:
# 1. Push events to the main branch
# 2. Pull request events
on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and Tag Docker Image
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Check whether the Dockerfile or any of its contents were modified
        id: changed-files
        uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94
        with:
          files_yaml: |
            api_reference_docker:
              - integrations/docker/**
            api_reference_docker_version:
              - integrations/docker/package.json

      - name: Set up Docker
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

      - name: Get version from package.json
        id: package-version
        working-directory: integrations/docker
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Build and tag Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: integrations/docker
          file: integrations/docker/Dockerfile
          push: false
          load: true
          # Linux-only at first
          platforms: linux/amd64
          tags: |
            scalarapi/api-reference:latest
            scalarapi/api-reference:${{ steps.package-version.outputs.VERSION }}

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        with:
          scan-type: 'config'
          scan-ref: 'integrations/docker/Dockerfile'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          retry-count: 3
          retry-delay: 30s

      - name: Log in to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: integrations/docker
          file: integrations/docker/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # With ARM
          platforms: linux/amd64,linux/arm64
          tags: |
            scalarapi/api-reference:latest
            scalarapi/api-reference:${{ steps.package-version.outputs.VERSION }}
