name: Lint SVG Icons

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/components/src/components/ScalarIcon/**'
      - 'packages/icons/src/icons/**'

jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint Component Library Icons
        run: pnpm --filter components lint:icons
      - name: Lint Icon Library Icons
        run: pnpm --filter icons lint:icons
