name: Test CDN Build (local)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Build packages
        uses: ./.github/actions/build-blacksmith
        with:
          node-version: ${{ matrix.node-version }}
          packages: './packages/**'
      - name: Get Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(npx playwright --version | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
      - name: Playwright binary cache
        uses: actions/cache@640a1c2554105b57832a23eea0b4672fc7a790d5
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Install Playwright dependencies
        run: npx playwright install-deps
      - name: Start HTML server
        run: pnpm --filter @scalar-examples/cdn-api-reference dev &
      - name: Run e2e tests (local)
        run: CI=1 pnpm test:e2e:local
